

all:
	g++ principal.cpp -I//home/darwin/opencv/opencvi/include/opencv4/ -L/home/darwin/opencv/opencvi/lib/ -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio -lopencv_objdetect -lopencv_ml -lopencv_dnn -o vision.bin


run:
	./vision.bin